# Generated by Django 3.0.7 on 2020-08-23 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerid', models.PositiveIntegerField()),
                ('graphql_id', models.CharField(max_length=250)),
                ('company', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('fax', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('merchant_id', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=15)),
                ('website', models.URLField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionid', models.CharField(max_length=250)),
                ('graphql_id', models.CharField(max_length=250)),
                ('amount', models.FloatField()),
                ('authorization_expires_at', models.DateTimeField()),
                ('currency_iso_code', models.CharField(max_length=10)),
                ('cvv_response_code', models.CharField(max_length=10)),
                ('discount_amount', models.FloatField()),
                ('gateway_rejection_reason', models.CharField(max_length=250)),
                ('master_merchant_account_id', models.CharField(max_length=250)),
                ('merchant_account_id', models.CharField(max_length=250)),
                ('network_response_code', models.CharField(max_length=250)),
                ('network_response_text', models.CharField(max_length=250)),
                ('network_transaction_id', models.CharField(max_length=250)),
                ('order_id', models.CharField(max_length=250)),
                ('payment_instrument_type', models.CharField(max_length=250)),
                ('plan_id', models.CharField(max_length=250)),
                ('processor_authorization_code', models.CharField(max_length=250)),
                ('processor_response_code', models.CharField(max_length=250)),
                ('processor_response_text', models.CharField(max_length=250)),
                ('processor_settlement_response_code', models.CharField(max_length=250)),
                ('processor_settlement_response_text', models.CharField(max_length=250)),
                ('retrieval_reference_number', models.CharField(max_length=250)),
                ('status', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='payment.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('amount', models.FloatField()),
                ('user', models.CharField(max_length=50)),
                ('transaction_source', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='payment.Transaction')),
            ],
        ),
        migrations.CreateModel(
            name='CreditCardDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=250)),
                ('binnumber', models.PositiveIntegerField()),
                ('last_4', models.PositiveIntegerField()),
                ('card_type', models.CharField(max_length=50)),
                ('expiration_month', models.PositiveIntegerField()),
                ('expiration_year', models.PositiveIntegerField()),
                ('customer_location', models.CharField(max_length=5)),
                ('cardholder_name', models.CharField(max_length=50)),
                ('image_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_card', to='payment.Transaction')),
            ],
        ),
    ]
