# Generated by Django 3.0.7 on 2020-08-23 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customerid',
            field=models.CharField(max_length=250),
        ),
    ]
