# Generated by Django 3.0.7 on 2020-08-23 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_auto_20200823_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='authorization_expires_at',
            field=models.CharField(max_length=250),
        ),
    ]
