# Generated by Django 3.0.7 on 2020-08-24 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_transaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcarddetails',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='statushistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='merchant_id',
            field=models.CharField(max_length=100),
        ),
    ]
