# Generated by Django 3.0.7 on 2020-07-22 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_last_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('null', 'Null'), ('normal', 'Normal'), ('business', 'Business')], max_length=20),
        ),
    ]
