# Generated by Django 3.0.2 on 2020-03-04 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_gallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessdetails',
            name='days',
        ),
        migrations.RemoveField(
            model_name='businessdetails',
            name='time',
        ),
    ]
