# Generated by Django 3.0.2 on 2020-03-05 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200304_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessdetails',
            name='business_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.BusinessInfo'),
        ),
    ]
