# Generated by Django 3.0.2 on 2020-03-05 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_businessdetails_business_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessdetails',
            name='business_info',
        ),
    ]
