# Generated by Django 3.0.2 on 2020-03-05 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_businessdetails_business_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_info', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
