# Generated by Django 3.0.2 on 2020-03-05 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200305_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessdetails',
            name='business_category',
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='business_type',
            field=models.CharField(choices=[('', 'Business type'), ('fashion', 'Fashion'), ('mobile & accessories', 'Mobile & Accessories'), ('restaurant', 'Restaurant'), ('money agent', 'Money Agent'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10),
        ),
    ]
