# Generated by Django 3.0.2 on 2020-03-05 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20200305_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessdetails',
            name='business_category',
            field=models.CharField(blank=True, choices=[('', 'Business type'), ('fashion', 'Fashion'), ('mobile & accessories', 'Mobile & Accessories'), ('restaurant', 'Restaurant'), ('money agent', 'Money Agent'), ('other', 'Other')], max_length=100, null=True),
        ),
    ]
