# Generated by Django 3.0.2 on 2020-03-13 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20200313_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessdetails',
            name='directions',
        ),
    ]
